apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flotta-edge-api-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flotta-edge-api-role
subjects:
- kind: ServiceAccount
  name: flotta-edge-api
  namespace: flotta