apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flotta-leader-election-rolebinding
  namespace: flotta
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flotta-leader-election-role
subjects:
- kind: ServiceAccount
  name: flotta-controller-manager
  namespace: flotta