apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: flotta/flotta-controller-manager
  name: flotta-controller-manager
  namespace: flotta
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|flotta|flotta-controller-manager'
---
apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: flotta/flotta-edge-api
  name: flotta-edge-api
  namespace: flotta
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|flotta|flotta-edge-api'
