apiVersion: v1
kind: PersistentVolume
metadata: # kpt-merge: /postgres-pv-volume
  name: postgres-pv-volume
  labels:
    type: local
  annotations:
    internal.kpt.dev/upstream-identifier: '|PersistentVolume|default|postgres-pv-volume'
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: # kpt-merge: /postgres-pv-claim
  name: postgres-pv-claim
  annotations:
    internal.kpt.dev/upstream-identifier: '|PersistentVolumeClaim|default|postgres-pv-claim'
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
