apiVersion: v1
kind: Service
metadata: # kpt-merge: /postgres
  name: postgres
  labels:
    app: postgres
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|postgres'
spec:
  type: NodePort
  ports:
  - port: 5432
  selector:
    app: postgres
