apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata: # kpt-merge: /example-configsync
  name: iot-workload-cluster-workload-cluster-configsync
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.porch.kpt.dev|PackageVariant|default|example-configsync'
spec:
  annotations:
    approval.nephio.org/policy: initial
  upstream:
    package: configsync
    repo: nephio-example-packages
    revision: v1
  downstream:
    package: iot-workload-cluster-workload-cluster-configsync
    repo: mgmt-staging
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: iot-workload-cluster
